name: Pipeline
on: [push]
env:
  ARTIFACT_NAME: python_hello_world.zip
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for Test
        uses: actions/checkout@v2
      - name: Run Scipt
        run: python hello.py
  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Checkout for build
        uses: actions/checkout@v2
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFIACT_NAME }}
          path: .
        
